import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import StyledComponentsRegistry from "./lib/registry";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Phimmoi | Phimmoi.net | Xem phim mới | Phim hay | Phim chiếu rạp",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AntdRegistry>
                    <AppRouterCacheProvider>
                        <StyledComponentsRegistry>
                            {children}
                        </StyledComponentsRegistry>
                    </AppRouterCacheProvider>
                </AntdRegistry>
            </body>
        </html>
    );
}
